services:
  - type: web
    name: nova-converter
    env: node
    rootDir: .
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y ghostscript libreoffice libreoffice-writer libreoffice-calc libreoffice-impress && \
      npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_CHAT_MODEL
        value: gpt-4o-mini
      - key: OPENAI_EMBEDDING_MODEL
        value: text-embedding-3-small
